### ISSUE TITLE
RuntimeError: Expected object of scalar type Bool but got scalar type Long for argument #2 'other'

### ISSUE THREAD

**Issue by raymondklutse** [lonePatient/Bert-Multi-Label-Text-Classification#16]
Thank you for this project. It has been very helpful. However, I am having  issues running the code based on the instructions presented. Here is the error I am getting. Any idea on how to get it fixed?

Traceback (most recent call last):
  File "run_bert.py", line 223, in <module>
    main()
  File "run_bert.py", line 216, in main
    run_train(args)
  File "run_bert.py", line 124, in run_train
    trainer.train(train_data=train_dataloader, valid_data=valid_dataloader, seed=args.seed)
  File "/home/raymond/Téléchargements/Bert-Multi-Label-Text-Classification-master/pybert/train/trainer.py", line 174, in train
    train_log = self.train_epoch(train_data)
  File "/home/raymond/Téléchargements/Bert-Multi-Label-Text-Classification-master/pybert/train/trainer.py", line 139, in train_epoch
    self.info[metric.name()] = metric.value()
  File "/home/raymond/Téléchargements/Bert-Multi-Label-Text-Classification-master/pybert/train/metrics.py", line 90, in value
    acc = np.mean(((self.y_pred>self.thresh)==self.y_true.byte()).float().cpu().numpy(), axis=1).sum()
RuntimeError: Expected object of scalar type Bool but got scalar type Byte for argument #2 'other'

**Comment by raymondklutse** [comment]
I fixed it. You have to change line 90 in metrics.py to 

 acc = np.mean((((self.y_pred>self.thresh).byte()==self.y_true.byte()).float().cpu().numpy()), axis=1).sum()
