### ISSUE TITLE
Seems some error in pickling train data

### ISSUE THREAD

**Issue by adiv5** [lonePatient/Bert-Multi-Label-Text-Classification#34]
I have followed all instructions as explained in readme, Now i try to run bert for training using command ` python run_bert.py --do_train --save_best --do_lower_case`
I am getting the following traceback.

```
  Traceback (most recent call last):
  File "run_bert.py", line 223, in <module>
    main()
  File "run_bert.py", line 216, in main
    run_train(args)
  File "run_bert.py", line 30, in run_train
    train_data = processor.get_train(config['data_dir'] / f"{args.data_name}.train.pkl")
  File "/home/aditya/Projects/RD/Bert-Multi-Label-Text-Classification/pybert/io/bert_processor.py", line 46, in get_train
    return self.read_data(data_file)
  File "/home/aditya/Projects/RD/Bert-Multi-Label-Text-Classification/pybert/io/bert_processor.py", line 63, in read_data
    lines = load_pickle(input_file)
  File "/home/aditya/Projects/RD/Bert-Multi-Label-Text-Classification/pybert/common/tools.py", line 148, in load_pickle
    with open(str(input_file), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'pybert/dataset/kaggle.train.pkl'
```

I suspect that the training data requires pickling before it can be used in algo. However pickling Mechanism is defined in TaskData class in `io.task_data.py`. But in `run_bert.py` we are not using it.
I feel there is some missing code in `run_train` function of `run_bert.py` How to handle this condition?

**Comment by lonePatient** [comment]
@adiv5,hi you should `do_data` before `do_train`

```text
1. Run python run_bert.py --do_data to preprocess data.

2. Run python run_bert.py --do_train --save_best --do_lower_case to fine tuning bert model.

3. Run run_bert.py --do_test --do_lower_case to predict new data.
```

**Comment by adiv5** [comment]
Thanks for the suggestion, I will try that
