### ISSUE TITLE
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got CPUType instead (while checking arguments for embedding)

### ISSUE THREAD

**Issue by wannibar** [lonePatient/Bert-Multi-Label-Text-Classification#6]
when I run this repo. i first get encoding error in utils.py and i solve it by import io library and with open by pass encoding='utf-8'. by when i run " python train_bert_multi_label.py", i get  following error....

[2019-06-23 16:47:10]: bert train_bert_multi_label.py[line:75] INFO  initializing model
[2019-06-23 16:47:16]: bert train_bert_multi_label.py[line:98] INFO  initializing callbacks
[2019-06-23 16:47:16]: bert train_bert_multi_label.py[line:116] INFO  training model....
[2019-06-23 16:47:16]: bert utils.py[line:23] WARNING  Warning: There's no GPU available on this machine, training will be performed on CPU.
model summary info:
Traceback (most recent call last):
  File "train_bert_multi_label.py", line 144, in <module>
    main()
  File "train_bert_multi_label.py", line 138, in main
    trainer.train(train_data = train_loader,valid_data=valid_loader)
  File "E:\迅雷下载\Bert-Multi-Label-Text-Classification-master\Bert-Multi-Label-Text-Classification-master\pybert\train\trainer.py", line 167, in train
    summary(self.model,*(input_ids, segment_ids,input_mask),show_input=True)
  File "E:\迅雷下载\Bert-Multi-Label-Text-Classification-master\Bert-Multi-Label-Text-Classification-master\pybert\utils\utils.py", line 190, in summary
    model(*inputs)
  File "C:\soft\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\迅雷下载\Bert-Multi-Label-Text-Classification-master\Bert-Multi-Label-Text-Classification-master\pybert\model\nn\bert_fine.py", line 28, in forward
    output_all_encoded_layers=output_all_encoded_layers)
  File "C:\soft\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\soft\Anaconda3\lib\site-packages\pytorch_pretrained_bert\modeling.py", line 730, in forward
    embedding_output = self.embeddings(input_ids, token_type_ids)
  File "C:\soft\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\soft\Anaconda3\lib\site-packages\pytorch_pretrained_bert\modeling.py", line 267, in forward
    words_embeddings = self.word_embeddings(input_ids)
  File "C:\soft\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\soft\Anaconda3\lib\site-packages\torch\nn\modules\sparse.py", line 117, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "C:\soft\Anaconda3\lib\site-packages\torch\nn\functional.py", line 1506, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got CPUType instead (while checking arguments for embedding)

anybody knows how to solve it~ QAQ

**Comment by GodQiu** [comment]
I have ever encounter the problem, have you ever solved it? Can you share me how to solve it.
