### ISSUE TITLE
undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE

### ISSUE THREAD

**Issue by loveJasmine** [lonePatient/Bert-Multi-Label-Text-Classification#8]
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/Bert-Multi-Label-Text-Classification$ python3.6 train_bert_multi_label.py
[2019-06-24 20:44:24]: bert train_bert_multi_label.py[line:26] INFO  seed is 2018
[2019-06-24 20:44:24]: bert train_bert_multi_label.py[line:29] INFO  starting load data from disk
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 159571/159571 [00:14<00:00, 10903.56it/s]
[2019-06-24 20:44:40]: bert data_transformer.py[line:83] INFO  train val split
Merge: 159571it [00:00, 989703.96it/s]
write data to disk: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 127657/127657 [00:00<00:00, 131160.91it/s]
write data to disk: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31914/31914 [00:00<00:00, 125464.80it/s]
[2019-06-24 20:44:44]: bert train_bert_multi_label.py[line:75] INFO  initializing model
Traceback (most recent call last):
  File "train_bert_multi_label.py", line 144, in <module>
    main()
  File "train_bert_multi_label.py", line 78, in main
    num_classes = len(id2label))
  File "/usr/local/lib/python3.6/dist-packages/pytorch_pretrained_bert/modeling.py", line 600, in from_pretrained
    model = cls(config, *inputs, **kwargs)
  File "/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/Bert-Multi-Label-Text-Classification/pybert/model/nn/bert_fine.py", line 8, in __init__
    self.bert = BertModel(bertConfig) # bert模型
  File "/usr/local/lib/python3.6/dist-packages/pytorch_pretrained_bert/modeling.py", line 704, in __init__
    self.embeddings = BertEmbeddings(config)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_pretrained_bert/modeling.py", line 257, in __init__
    self.LayerNorm = BertLayerNorm(config.hidden_size, eps=1e-12)
  File "/usr/local/lib/python3.6/dist-packages/apex/normalization/fused_layer_norm.py", line 126, in __init__
    fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /usr/local/lib/python3.6/dist-packages/fused_layer_norm_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/Bert-Multi-Label-Text-Classification$

**Comment by loveJasmine** [comment]
rebuild apex can fix this error
